#!/bin/sh -e

PUSH_RABBITMQ="false"
PUSH_JDK="false"
PUSH_H2D="false"
PUSH_CONFIG_SERVER="false"
PUSH_DATAFLOW_SOURCE_SERVER="false"
PUSH_DATAFLOW_PROCESS_SERVER="false"
PUSH_DATAFLOW_SINK_SERVER="false"
