#!/bin/bash -e
export APP_DESCR="Customization of Spring Cloud Config Server"
export APP_NAME="dataflow-ms-config-server"
export MAIN_CLASS="com.dataflow.flow.centric.ms.config.server.ConfigServerApplication"
export LOG_LEVEL="spring"
export CONFIG_FILE_PATH="/opt/spring-cloud-group/dataflow-ms-config-server/config/$APP_GROUP_FOLDER/$APP_ENV_FOLDER/application-$CONFIG_SERVER_ENV.$CONFIG_SERVER_FORMAT"
export APP_ARGS="--spring.config.location=$CONFIG_FILE_PATH"
export JVM_ARGS="-Xms1536m -Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom"
export APP_GROUP="$APP_GROUP_FOLDER"
export REDIRECT_OUTPUT_TO_APP="yes"
