#!/bin/bash -e
export APP_DESCR="Flow Centric Spring Dataflow Source Service"
export APP_NAME="dataflow-ms-flow-centric-source-poc"
export MAIN_CLASS="com.dataflow.flow.centric.ms.source.FlowCentricSourceApplication"
export LOG_LEVEL="service"
export APP_ARGS="--spring.profiles.active=source-compose --spring.cloud.config.uri=http://$CONFIG_SERVER_HOSTNAME:$CONFIG_SERVER_PORT --envt=D --envtPath=3 --envtLower=d --envtStrUpper=DEV --envtStrLower=dev --envtServerNum=01"
export JVM_ARGS="-Xms1536m -Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom"
#export JVM_ARGS="-XX:+PrintGCDetails"
export APP_GROUP="dataflow-flow-centric"
export REDIRECT_OUTPUT_TO_APP="no"
